# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Thomas Chadefaux
# Description of the Site
description: ""
# URL of Image of the Site
site-image: /WhatATheme/assets/images/paceLogo.png #meta.jpg
site-cv: /WhatATheme/assets/images/cv.pdf #meta.jpg
# Keywords of the Site
site-keywords: chadefaux
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /WhatATheme/assets/images/agincourt.jpg #meta.jpg
#https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: chadefat@tcd.ie
#facebook_username: 
#twitter_username: 
#instagram_username: 
#linkedin_username: 
github_username:  chadefa1
#youtube_channel_id: UCk_93NXYP-U_AOB5GfWlOow
#reddit_username: /
#behance_username: /
#dribbble_username: /
#spotify_username: /

# Google Analytics
google-analytics: 
#UA-163806439-1

# Disqus
#disqus-shortname: chadefaux

# Name of the Author
author-name: Thomas Chadefaux
# URL for the Image of the Author
author-image: /WhatATheme/assets/images/chadefauxERC.jpg
# 60 Words About the Author
author-about: I am an Assistant Professor of Political Science at Trinity College Dublin. <br> My current research focuses on the causes of interstate conflict and on their prediction. In particular, I rely on large amounts of fine-grained spatial and temporal data (e.g., newspapers, satellite images, financial markets) to reveal early warning signals for war. 
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/chadefa1

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

collections:
  publications:
    output: true
    
# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
